server:
  port: 9080

spring:
  application:
    name: auth-service
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-auth.yml
      - optional:classpath:application-jpa.yml
      - optional:classpath:application-kafka.yml
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/apten_auth?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: qaws7579
  kafka:
    consumer:
      group-id: auth-service-group
  data:
    redis:
      host: localhost # Redis 호스트
      port: 6379 # Redis 포트

coolsms:
  api-key: ${COOLSMS_API_KEY} # Coolsms API 키
  api-secret: ${COOLSMS_API_SECRET} # Coolsms API 시크릿
  from: ${COOLSMS_FROM_NUMBER} # 발신번호

constants:
  api:
    prefix: /api/auth

springdoc:
  api-docs:
    enabled: true