server:
  port: 9084

spring:
  application:
    name: household-service
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-jpa.yml
      - optional:classpath:application-kafka.yml
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${HOUSEHOLD_DB_URL}
    username: ${HOUSEHOLD_DB_USERNAME}
    password: ${HOUSEHOLD_DB_PASSWORD}
  kafka:
    consumer:
      group-id: household-service-group

constants:
  api:
    prefix: /api/households
