server:
  port: 9083

spring:
  application:
    name: parking-vehicle-service
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-jpa.yml
      - optional:classpath:application-kafka.yml
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${PARKING_DB_URL}
    username: ${PARKING_DB_USERNAME}
    password: ${PARKING_DB_PASSWORD}
  kafka:
    consumer:
      group-id: parking-vehicle-service-group

constants:
  api:
    prefix: /api
