server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: facility-reservation-service
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-jpa.yml
      - optional:classpath:application-kafka.yml
      - optional:classpath:application-redis-prod.yml
      - optional:file:../.env[.properties]
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${FACILITY_DB_URL}
    username: ${FACILITY_DB_USERNAME}
    password: ${FACILITY_DB_PASSWORD}
  kafka:
    consumer:
#      group-id: facility-reservation-service-group

constants:
  api:
    prefix: /api

apten:
  outbox:
    enabled: true
  bootstrap:
    facility-type:
      enabled: ${APTEN_BOOTSTRAP_FACILITY_TYPE_ENABLED:true}
  scheduler:
    reservation-complete:
      enabled: ${APTEN_SCHEDULER_RESERVATION_COMPLETE_ENABLED:true}
      fixed-delay-ms: ${APTEN_SCHEDULER_RESERVATION_COMPLETE_FIXED_DELAY_MS:60000}
      batch-size: ${APTEN_SCHEDULER_RESERVATION_COMPLETE_BATCH_SIZE:100}
    gx-complete:
      enabled: ${APTEN_SCHEDULER_GX_COMPLETE_ENABLED:true}
      fixed-delay-ms: ${APTEN_SCHEDULER_GX_COMPLETE_FIXED_DELAY_MS:60000}
      batch-size: ${APTEN_SCHEDULER_GX_COMPLETE_BATCH_SIZE:100}
