package com.apten.common.kafka;

// 캐시 동기화에서 사용하는 공통 이벤트 타입 목록
public enum EventType {
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    APARTMENT_COMPLEX_CREATED,
    APARTMENT_COMPLEX_UPDATED,
    APARTMENT_COMPLEX_DEACTIVATED,
    HOUSEHOLD_CREATED,
    HOUSEHOLD_UPDATED,
    HOUSEHOLD_DEACTIVATED,
    HOUSEHOLD_MEMBER_CREATED,
    HOUSEHOLD_MEMBER_UPDATED,
    HOUSEHOLD_MEMBER_REMOVED
}
