package com.apten.common.kafka;

// 캐시 동기화와 도메인 이벤트 전달에 사용하는 공통 이벤트 타입이다.
public enum EventType {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_DEACTIVATED,

    APARTMENT_COMPLEX_CREATED,
    APARTMENT_COMPLEX_UPDATED,
    APARTMENT_COMPLEX_DEACTIVATED,

    HOUSEHOLD_CREATED,
    HOUSEHOLD_UPDATED,
    HOUSEHOLD_DELETED,
    HOUSEHOLD_DEACTIVATED,
    HOUSEHOLD_MEMBER_CREATED,
    HOUSEHOLD_MEMBER_UPDATED,
    HOUSEHOLD_MEMBER_DELETED,
    HOUSEHOLD_MEMBER_REMOVED,

    VEHICLE_APPROVED,
    VEHICLE_UPDATED,
    VEHICLE_DELETED,
    VEHICLE_STATUS_CHANGED,

    PARKING_SPOT_CHANGED,

    FACILITY_USAGE_COMPLETED,
    VISITOR_USAGE_SUMMARIZED,
    FACILITY_FEE_CALCULATED,

    HOUSEHOLD_MATCH_REQUESTED,
    HOUSEHOLD_MATCH_APPROVED,
    HOUSEHOLD_MATCH_REJECTED,

    // 서비스 → notification-service 알림 생성 요청 (전 서비스 공용)
    NOTIFICATION_REQUESTED,
    ADMIN_NOTIFICATION_REQUESTED
}
