server:
  port: 9082

spring:
  application:
    name: apartment-complex-service
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-jpa.yml
      - optional:classpath:application-kafka.yml
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${COMPLEX_DB_URL}
    username: ${COMPLEX_DB_USERNAME}
    password: ${COMPLEX_DB_PASSWORD}
  kafka:
    consumer:
      group-id: apartment-complex-service-group

constants:
  api:
    prefix: /api/apartment-complexes
