server:
  port: ${COMPLEX_SERVER_PORT}

spring:
  application:
    name: apartment-complex-service
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-jpa.yml
      - optional:classpath:application-kafka.yml
      - optional:file:../.env[.properties]
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${COMPLEX_DB_URL}
    username: ${COMPLEX_DB_USERNAME}
    password: ${COMPLEX_DB_PASSWORD}
  kafka:
    consumer:
#      group-id: apartment-complex-service-group

constants:
  api:
    prefix: /api/apartment-complexes

apten:
  outbox:
    enabled: true
