# 공통 JWT 설정
constants:
  jwt:
    issuer: apten-auth-service
    bearer-format: Bearer
    claim-key: role
    secret-key: ${JWT_SECRET_KEY:APTeN-MSA-Local-Secret-Key-Change-Me}
    access-token:
      name: access-token
      expiration-seconds: 3600
    refresh-token:
      name: refresh-token
      expiration-seconds: 1209600

security:
  jwt:
    secret: ${constants.jwt.secret-key}
    access-token-expiration: 3600000
    refresh-token-expiration: 1209600000
